---

- name: "Install dependencies Nodejs NPM"
  become: yes
  apt: 
    name: ["nodejs","npm"]
    state: present
    update_cache: yes
      
- name: "install pm2 globally"
  become: yes
  become_method: sudo
  npm:
    name: pm2
    global: yes
    state: present
