---

- name: "Install dependencies Nodejs NPM"
  become: yes
  apt: 
    name: ["nodejs","npm"]
    state: present
    update_cache: yes
      
- name: "install pm2 globally"
  become: yes
  shell: |
    cd/home/ubuntu/npm install pm2 -g
  
