---

- name: "extract artifact."
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/
    owner: ubuntu
    remote_src: no

- name: "stop app."
  shell: pm2 stop default
  ignore_errors: yes

- name: "start app."
  environment: 
  shell: |
    cd dist
    echo `pwd` >> ansible-test.txt
    pm2 start main.js --name backend
