---

- name: "extract artifact."
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/

- name: "stop app."
  shell: pm2 stop default
  ignore_errors: yes

- name: "start app."
  environment: 
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}" 
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}" 
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}" 
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}" 
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}" 
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "./src/modules/**/*.entity.ts"
    TYPEORM_MIGRATIONS: "./src/migrations/*.ts"
  shell: |
    npm install
    cd ~/home/ubuntu
    tar -xzvf backend_artifact.tar.gz -C backend
    rm backend_artifact.tar.gz
    cd backend/
    npm install
    npm audit fix && npm run build
    cd dist
    echo `pwd` >> ansible-test.txt
    pm2 start npm --name backend -- start
