---

- name: "extract artifact."
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/

- name: "stop app."
  shell: pm2 stop default
  ignore_errors: yes

- name: "start app."
  environment: 
  shell: |
    cd dist
    echo `pwd` >> ansible-test.txt
    pm2 start npm --name backend -- start
