---

- name: "extract artifact."
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/
    owner: ubuntu
    remote_src: no

- name: "stop app."
  shell: pm2 stop default
  ignore_errors: yes

- name: "start app."
  environment: 
  shell: |
    export TYPEORM_CONNECTION="postgres"
    export TYPEORM_MIGRATIONS_DIR="./src/migrations"
    export TYPEORM_ENTITIES="./src/modules/domain/**/*.entity.ts"
    export TYPEORM_MIGRATIONS="./src/migrations/*.ts"
    export TYPEORM_HOST="ec2-15-207-114-202.ap-south-1.compute.amazonaws.com"
    export TYPEORM_PORT="5432"
    export TYPEORM_USERNAME="glee"
    export TYPEORM_PASSWORD="glee"
    export TYPEORM_DATABASE="postgres"
    cd dist
    echo `pwd` >> ansible-test.txt
    pm2 start main.js --name backend
